runtime: nodejs16
instance_class: F1
env: standard
inbound_services:
- warmup
automatic_scaling:
  max_instances: 5
  target_cpu_utilization: 0.95
  max_concurrent_requests: 25
  max_pending_latency: automatic
  min_pending_latency: 500ms